version: "3.3"
services:
  powerx:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment: 
      - GIN_MODE=release
    ports:
      - ${PORT:-8003}:8080
    volumes:
      - ./config.yml:/app/config.yml
      - ./configs:/app/configs
      - ./resources:/app/resources
      - ../certs:/certs
      - /var/log/ArtisanCloud:/var/log/ArtisanCloud
