package menu

import (
	admdto "github.com/ArtisanCloud/PowerX/internal/transport/http/admin/dto"
	"github.com/ArtisanCloud/PowerX/pkg/plugin_mgr"
)

func BuildSystemMenus() []admdto.AdminMenuItem {
	return []admdto.AdminMenuItem{
		{
			Key:     plugin_mgr.KeyAgent,
			Title:   "menu.agent",
			Icon:    "i-heroicons-sparkles",
			URL:     "/agent",
			Order:   1,
			Visible: true,
			Origin:  plugin_mgr.OriginSystem,
			Slot:    plugin_mgr.SlotRoot,
		},
		{
			Key:         "skill_management",
			Title:       "menu.skills",
			Icon:        "i-heroicons-squares-plus",
			URL:         "/settings/ai/skills",
			Order:       2,
			Visible:     true,
			Origin:      plugin_mgr.OriginSystem,
			Slot:        plugin_mgr.SlotRoot,
			Permissions: []string{"admin:root"},
		},
		{
			Key:     plugin_mgr.KeyKnowledgeSpace,
			Title:   "menu.knowledgeSpace",
			Icon:    "i-heroicons-book-open",
			URL:     "/knowledge-spaces",
			Order:   3,
			Visible: true,
			Origin:  plugin_mgr.OriginSystem,
			Slot:    plugin_mgr.SlotRoot,
		},
		{
			Key:     plugin_mgr.KeyWorkflow,
			Title:   "menu.workflow",
			Icon:    "i-heroicons-arrow-path-rounded-square",
			URL:     "/workflow",
			Order:   4,
			Visible: true,
			Origin:  plugin_mgr.OriginSystem,
			Slot:    plugin_mgr.SlotRoot,
		},
		{
			Key:     plugin_mgr.KeyMedia,
			Title:   "menu.media",
			Icon:    "i-heroicons-photo",
			URL:     "/content/media",
			Order:   5,
			Visible: true,
			Origin:  plugin_mgr.OriginSystem,
			Slot:    plugin_mgr.SlotRoot,
		},
		{
			Key:     plugin_mgr.KeyDashboard,
			Title:   "menu.dashboard",
			Icon:    "i-heroicons-arrow-trending-up",
			URL:     "/dashboard",
			Order:   6,
			Visible: true,
			Origin:  plugin_mgr.OriginSystem,
			Slot:    plugin_mgr.SlotRoot,
		},
		{
			Key:         "monitor_center",
			Title:       "menu.monitorCenter",
			Icon:        "i-heroicons-eye",
			URL:         "/monitor/event-bus",
			Order:       7,
			Visible:     true,
			Origin:      plugin_mgr.OriginSystem,
			Slot:        plugin_mgr.SlotRoot,
			Permissions: []string{"admin:root"},
			Children: []admdto.AdminMenuItem{
				{
					Key:         "monitor_event_bus",
					Title:       "事件总线",
					Icon:        "i-heroicons-queue-list",
					URL:         "/monitor/event-bus",
					Order:       1,
					Visible:     true,
					Origin:      plugin_mgr.OriginSystem,
					ParentID:    "monitor_center",
					Permissions: []string{"admin:root"},
				},
				{
					Key:         "monitor_websocket",
					Title:       "WebSocket",
					Icon:        "i-heroicons-signal",
					URL:         "/monitor/websocket",
					Order:       2,
					Visible:     true,
					Origin:      plugin_mgr.OriginSystem,
					ParentID:    "monitor_center",
					Permissions: []string{"admin:root"},
				},
				{
					Key:         "monitor_task_cron",
					Title:       "Task / Cron",
					Icon:        "i-heroicons-command-line",
					URL:         "/monitor/task-cron",
					Order:       3,
					Visible:     true,
					Origin:      plugin_mgr.OriginSystem,
					ParentID:    "monitor_center",
					Permissions: []string{"admin:root"},
				},
				{
					Key:         "monitor_logs_trace",
					Title:       "Logs / Trace",
					Icon:        "i-heroicons-document-magnifying-glass",
					URL:         "/monitor/logs-trace",
					Order:       4,
					Visible:     true,
					Origin:      plugin_mgr.OriginSystem,
					ParentID:    "monitor_center",
					Permissions: []string{"admin:root"},
				},
			},
		},
		{
			Key:         plugin_mgr.KeyPlugins,
			Title:       "menu.openMarket",
			Icon:        "i-heroicons-puzzle-piece",
			Order:       8,
			Visible:     true,
			Origin:      plugin_mgr.OriginSystem,
			Slot:        plugin_mgr.SlotRoot,
			Permissions: []string{"admin:root"}, // 仅 root 可见
			Children: []admdto.AdminMenuItem{
				{
					Key:         "plugin_market",
					Title:       "menu.pluginMarketplace",
					Icon:        "i-heroicons-building-storefront",
					URL:         "/plugins/market",
					Order:       1,
					Visible:     true,
					Origin:      plugin_mgr.OriginSystem,
					ParentID:    plugin_mgr.KeyPlugins,
					Permissions: []string{"admin:root"},
				},
				{
					Key:         "plugin_release",
					Title:       "menu.pluginReleaseCandidates",
					Icon:        "i-heroicons-queue-list",
					URL:         "/plugin-release",
					Order:       4,
					Visible:     true,
					Origin:      plugin_mgr.OriginSystem,
					ParentID:    plugin_mgr.KeyPlugins,
					Permissions: []string{"admin:root"},
				},
				{
					Key:         "plugin_capabilities",
					Title:       "menu.pluginCapabilities",
					Icon:        "i-heroicons-table-cells",
					URL:         "/settings/ai/capability-registry",
					Order:       2,
					Visible:     true,
					Origin:      plugin_mgr.OriginSystem,
					ParentID:    plugin_mgr.KeyPlugins,
					Permissions: []string{"admin:root"},
				},
				{
					Key:         "platform_connectors",
					Title:       "menu.intelligentPlatforms",
					Icon:        "i-heroicons-link",
					URL:         "/settings/ai/connectors",
					Order:       3,
					Visible:     true,
					Origin:      plugin_mgr.OriginSystem,
					ParentID:    plugin_mgr.KeyPlugins,
					Permissions: []string{"admin:root"},
				},
			},
		},
		{
			Key:     plugin_mgr.KeySettings,
			Title:   "menu.settings",
			Icon:    "i-heroicons-cog-6-tooth",
			Order:   9,
			Visible: true,
			Origin:  plugin_mgr.OriginSystem,
			Children: []admdto.AdminMenuItem{
				{
					Key:      plugin_mgr.KeyUserManagement,
					Title:    "menu.userManagement",
					Icon:     "i-heroicons-users",
					URL:      "/settings/users",
					Order:    1,
					Visible:  true,
					Origin:   plugin_mgr.OriginSystem,
					ParentID: plugin_mgr.KeySettings,
				},
				{
					Key:      plugin_mgr.KeyRoleManagement,
					Title:    "menu.roleManagement",
					Icon:     "i-heroicons-key",
					URL:      "/settings/roles",
					Order:    2,
					Visible:  true,
					Origin:   plugin_mgr.OriginSystem,
					ParentID: plugin_mgr.KeySettings,
					Permissions: []string{
						"admin:tenant",
					},
				},
				{
					Key:      plugin_mgr.KeySystemConfig,
					Title:    "menu.systemConfig",
					Icon:     "i-heroicons-wrench-screwdriver",
					URL:      "/settings/config",
					Order:    3,
					Visible:  true,
					Origin:   plugin_mgr.OriginSystem,
					ParentID: plugin_mgr.KeySettings,
					Permissions: []string{
						"admin:tenant",
					},
				},
				{
					Key:      plugin_mgr.KeyAISettings,
					Title:    "menu.aiSettings",
					Icon:     "i-heroicons-cpu-chip",
					URL:      "/settings/ai",
					Order:    4,
					Visible:  true,
					Origin:   plugin_mgr.OriginSystem,
					ParentID: plugin_mgr.KeySettings,
					Permissions: []string{
						"admin:tenant",
					},
					Children: []admdto.AdminMenuItem{
						{
							Key:      plugin_mgr.KeyAISettingsModel,
							Title:    "menu.aiSettingsModel",
							Icon:     "i-heroicons-cog-6-tooth",
							URL:      "/settings/ai",
							Order:    1,
							Visible:  true,
							Origin:   plugin_mgr.OriginSystem,
							ParentID: plugin_mgr.KeyAISettings,
							Permissions: []string{
								"admin:tenant",
							},
						},
						{
							Key:      plugin_mgr.KeyAISettingsCost,
							Title:    "menu.aiSettingsCost",
							Icon:     "i-heroicons-banknotes",
							URL:      "/settings/ai/cost",
							Order:    2,
							Visible:  true,
							Origin:   plugin_mgr.OriginSystem,
							ParentID: plugin_mgr.KeyAISettings,
							Permissions: []string{
								"admin:tenant",
							},
						},
						{
							Key:      plugin_mgr.KeyAISettingsContextOptimizer,
							Title:    "menu.aiSettingsContextOptimizer",
							Icon:     "i-heroicons-adjustments-horizontal",
							URL:      "/settings/ai/context-optimizer",
							Order:    3,
							Visible:  true,
							Origin:   plugin_mgr.OriginSystem,
							ParentID: plugin_mgr.KeyAISettings,
							Permissions: []string{
								"admin:tenant",
							},
						},
					},
				},
				{
					Key:      "integration_api_keys",
					Title:    "API Key 管理",
					Icon:     "i-heroicons-key",
					URL:      "/settings/integration-api-keys",
					Order:    5,
					Visible:  true,
					Origin:   plugin_mgr.OriginSystem,
					ParentID: plugin_mgr.KeySettings,
				},
			},
		},
	}
}
