package menu

import (
	admdto "github.com/ArtisanCloud/PowerX/internal/transport/http/admin/dto"
	"github.com/ArtisanCloud/PowerX/pkg/plugin_mgr"
)

func BuildSystemMenus() []admdto.AdminMenuItem {
	return []admdto.AdminMenuItem{
		{
			Key:     plugin_mgr.KeyAgent,
			Title:   "menu.agent",
			Icon:    "i-heroicons-sparkles",
			URL:     "/agent",
			Order:   1,
			Visible: true,
			Origin:  plugin_mgr.OriginSystem,
			Slot:    plugin_mgr.SlotRoot,
			Permissions: []string{
				"menu:agent:read",
			},
			Children: []admdto.AdminMenuItem{
				{
					Key:      "agent_chat",
					Title:    "智能会话",
					Icon:     "i-heroicons-chat-bubble-left-right",
					URL:      "/agent/sessions",
					Order:    1,
					Visible:  true,
					Origin:   plugin_mgr.OriginSystem,
					ParentID: plugin_mgr.KeyAgent,
					Permissions: []string{
						"menu:agent.chat:read",
					},
				},
				{
					Key:      "agent_management",
					Title:    "智能体管理",
					Icon:     "i-heroicons-squares-2x2",
					URL:      "/settings/ai/agents",
					Order:    2,
					Visible:  true,
					Origin:   plugin_mgr.OriginSystem,
					ParentID: plugin_mgr.KeyAgent,
					Permissions: []string{
						"admin:tenant",
						"menu:agent.management:read",
					},
				},
				{
					Key:      "agent_team",
					Title:    "团队管理",
					Icon:     "i-heroicons-user-group",
					URL:      "/settings/ai/agent-teams",
					Order:    3,
					Visible:  true,
					Origin:   plugin_mgr.OriginSystem,
					ParentID: plugin_mgr.KeyAgent,
					Permissions: []string{
						"admin:tenant",
						"menu:agent.team:read",
					},
				},
				{
					Key:      "agent_team_tasks",
					Title:    "团队任务",
					Icon:     "i-heroicons-list-bullet",
					URL:      "/agent/team-tasks",
					Order:    5,
					Visible:  true,
					Origin:   plugin_mgr.OriginSystem,
					ParentID: plugin_mgr.KeyAgent,
					Permissions: []string{
						"menu:agent.team_tasks:read",
					},
				},
				{
					Key:      "agent_traces",
					Title:    "Agent 运行追踪",
					Icon:     "i-heroicons-document-magnifying-glass",
					URL:      "/agent/traces",
					Order:    7,
					Visible:  true,
					Origin:   plugin_mgr.OriginSystem,
					ParentID: plugin_mgr.KeyAgent,
					Permissions: []string{
						"admin:root",
						"menu:agent.traces:read",
					},
				},
			},
		},
		{
			Key:         "skill_management",
			Title:       "menu.skills",
			Icon:        "i-heroicons-squares-plus",
			URL:         "/settings/ai/skills",
			Order:       2,
			Visible:     true,
			Origin:      plugin_mgr.OriginSystem,
			Slot:        plugin_mgr.SlotRoot,
			Permissions: []string{"admin:root", "menu:skills:read"},
		},
		{
			Key:     plugin_mgr.KeyKnowledgeSpace,
			Title:   "menu.knowledgeSpace",
			Icon:    "i-heroicons-book-open",
			URL:     "/knowledge-spaces",
			Order:   3,
			Visible: true,
			Origin:  plugin_mgr.OriginSystem,
			Slot:    plugin_mgr.SlotRoot,
			Permissions: []string{
				"menu:knowledge:read",
			},
		},
		{
			Key:     plugin_mgr.KeyWorkflow,
			Title:   "menu.workflow",
			Icon:    "i-heroicons-arrow-path-rounded-square",
			URL:     "/workflow",
			Order:   4,
			Visible: true,
			Origin:  plugin_mgr.OriginSystem,
			Slot:    plugin_mgr.SlotRoot,
			Permissions: []string{
				"menu:workflow:read",
			},
		},
		{
			Key:     plugin_mgr.KeyMedia,
			Title:   "menu.media",
			Icon:    "i-heroicons-photo",
			URL:     "/content/media",
			Order:   5,
			Visible: true,
			Origin:  plugin_mgr.OriginSystem,
			Slot:    plugin_mgr.SlotRoot,
			Permissions: []string{
				"menu:media:read",
			},
		},
		{
			Key:     plugin_mgr.KeyDashboard,
			Title:   "menu.dashboard",
			Icon:    "i-heroicons-arrow-trending-up",
			URL:     "/dashboard",
			Order:   6,
			Visible: true,
			Origin:  plugin_mgr.OriginSystem,
			Slot:    plugin_mgr.SlotRoot,
			Permissions: []string{
				"menu:dashboard:read",
			},
		},
		{
			Key:         "monitor_center",
			Title:       "menu.monitorCenter",
			Icon:        "i-heroicons-eye",
			URL:         "/monitor/event-bus",
			Order:       7,
			Visible:     true,
			Origin:      plugin_mgr.OriginSystem,
			Slot:        plugin_mgr.SlotRoot,
			Permissions: []string{"admin:root", "menu:monitor:read"},
			Children: []admdto.AdminMenuItem{
				{
					Key:         "monitor_event_bus",
					Title:       "事件总线",
					Icon:        "i-heroicons-queue-list",
					URL:         "/monitor/event-bus",
					Order:       1,
					Visible:     true,
					Origin:      plugin_mgr.OriginSystem,
					ParentID:    "monitor_center",
					Permissions: []string{"admin:root", "menu:monitor:read"},
				},
				{
					Key:         "monitor_websocket",
					Title:       "WebSocket",
					Icon:        "i-heroicons-signal",
					URL:         "/monitor/websocket",
					Order:       2,
					Visible:     true,
					Origin:      plugin_mgr.OriginSystem,
					ParentID:    "monitor_center",
					Permissions: []string{"admin:root", "menu:monitor:read"},
				},
				{
					Key:         "monitor_task_cron",
					Title:       "后台任务",
					Icon:        "i-heroicons-command-line",
					URL:         "/monitor/task-cron",
					Order:       3,
					Visible:     true,
					Origin:      plugin_mgr.OriginSystem,
					ParentID:    "monitor_center",
					Permissions: []string{"admin:root", "menu:monitor:read"},
				},
				{
					Key:         "monitor_logs_trace",
					Title:       "Logs / Trace",
					Icon:        "i-heroicons-document-magnifying-glass",
					URL:         "/monitor/logs-trace",
					Order:       4,
					Visible:     true,
					Origin:      plugin_mgr.OriginSystem,
					ParentID:    "monitor_center",
					Permissions: []string{"admin:root", "menu:monitor:read"},
				},
				{
					Key:         "monitor_backup_center",
					Title:       "备份中心",
					Icon:        "i-heroicons-circle-stack",
					URL:         "/ops/backup",
					Order:       5,
					Visible:     true,
					Origin:      plugin_mgr.OriginSystem,
					ParentID:    "monitor_center",
					Permissions: []string{"admin:root", "menu:monitor:read"},
				},
			},
		},
		{
			Key:         plugin_mgr.KeyPlugins,
			Title:       "menu.pluginMarketplace",
			Icon:        "i-heroicons-puzzle-piece",
			Order:       8,
			Visible:     true,
			Origin:      plugin_mgr.OriginSystem,
			Slot:        plugin_mgr.SlotRoot,
			Permissions: []string{"admin:root", "admin:tenant", "menu:plugins:read"},
			Children: []admdto.AdminMenuItem{
				{
					Key:         "plugin_market",
					Title:       "menu.pluginManagement",
					Icon:        "i-heroicons-building-storefront",
					URL:         "/plugins/market",
					Order:       1,
					Visible:     true,
					Origin:      plugin_mgr.OriginSystem,
					ParentID:    plugin_mgr.KeyPlugins,
					Permissions: []string{"admin:root", "menu:plugins.market:read"},
				},
				{
					Key:         "plugin_subscriptions",
					Title:       "menu.pluginSubscriptions",
					Icon:        "i-heroicons-building-storefront",
					URL:         "/plugins/installed",
					Order:       1,
					Visible:     true,
					Origin:      plugin_mgr.OriginSystem,
					ParentID:    plugin_mgr.KeyPlugins,
					Permissions: []string{"admin:tenant_only", "menu:plugins.subscriptions:read"},
				},
				{
					Key:         "plugin_capabilities",
					Title:       "menu.pluginCapabilities",
					Icon:        "i-heroicons-table-cells",
					URL:         "/settings/ai/capability-registry",
					Order:       4,
					Visible:     true,
					Origin:      plugin_mgr.OriginSystem,
					ParentID:    plugin_mgr.KeyPlugins,
					Permissions: []string{"admin:root", "menu:plugins.capabilities:read"},
				},
				{
					Key:         "plugin_release",
					Title:       "menu.pluginReleaseCandidates",
					Icon:        "i-heroicons-queue-list",
					URL:         "/plugin-release",
					Order:       5,
					Visible:     true,
					Origin:      plugin_mgr.OriginSystem,
					ParentID:    plugin_mgr.KeyPlugins,
					Permissions: []string{"admin:root", "menu:plugins.release:read"},
				},
			},
		},
		{
			Key:     plugin_mgr.KeySettings,
			Title:   "menu.settings",
			Icon:    "i-heroicons-cog-6-tooth",
			Order:   9,
			Visible: true,
			Origin:  plugin_mgr.OriginSystem,
			Permissions: []string{
				"menu:settings:read",
			},
			Children: []admdto.AdminMenuItem{
				{
					Key:      plugin_mgr.KeyUserManagement,
					Title:    "menu.userManagement",
					Icon:     "i-heroicons-users",
					URL:      "/settings/users",
					Order:    1,
					Visible:  true,
					Origin:   plugin_mgr.OriginSystem,
					ParentID: plugin_mgr.KeySettings,
					Permissions: []string{
						"menu:settings.users:read",
					},
				},
				{
					Key:      plugin_mgr.KeyRoleManagement,
					Title:    "menu.roleManagement",
					Icon:     "i-heroicons-key",
					URL:      "/settings/roles",
					Order:    2,
					Visible:  true,
					Origin:   plugin_mgr.OriginSystem,
					ParentID: plugin_mgr.KeySettings,
					Permissions: []string{
						"admin:tenant",
						"menu:settings.roles:read",
					},
				},
				{
					Key:      plugin_mgr.KeySystemConfig,
					Title:    "menu.systemConfig",
					Icon:     "i-heroicons-wrench-screwdriver",
					URL:      "/settings/config",
					Order:    3,
					Visible:  true,
					Origin:   plugin_mgr.OriginSystem,
					ParentID: plugin_mgr.KeySettings,
					Permissions: []string{
						"admin:tenant",
						"menu:settings.config:read",
					},
				},
				{
					Key:      plugin_mgr.KeyMetadataGovernance,
					Title:    "menu.metadataGovernance",
					Icon:     "i-lucide-tags",
					URL:      "/settings/metadata-governance",
					Order:    4,
					Visible:  true,
					Origin:   plugin_mgr.OriginSystem,
					ParentID: plugin_mgr.KeySettings,
					Permissions: []string{
						"admin:tenant",
						"menu:settings.metadata_governance:read",
					},
				},
				{
					Key:      plugin_mgr.KeyAISettings,
					Title:    "menu.aiSettings",
					Icon:     "i-heroicons-cpu-chip",
					URL:      "/settings/ai",
					Order:    5,
					Visible:  true,
					Origin:   plugin_mgr.OriginSystem,
					ParentID: plugin_mgr.KeySettings,
					Permissions: []string{
						"admin:tenant",
						"menu:settings.ai:read",
					},
					Children: []admdto.AdminMenuItem{
						{
							Key:      plugin_mgr.KeyAISettingsModel,
							Title:    "menu.aiSettingsModel",
							Icon:     "i-heroicons-cog-6-tooth",
							URL:      "/settings/ai",
							Order:    1,
							Visible:  true,
							Origin:   plugin_mgr.OriginSystem,
							ParentID: plugin_mgr.KeyAISettings,
							Permissions: []string{
								"admin:tenant",
								"menu:settings.ai.model:read",
							},
						},
						{
							Key:      plugin_mgr.KeyAISettingsCost,
							Title:    "menu.aiSettingsCost",
							Icon:     "i-heroicons-banknotes",
							URL:      "/settings/ai/cost",
							Order:    2,
							Visible:  true,
							Origin:   plugin_mgr.OriginSystem,
							ParentID: plugin_mgr.KeyAISettings,
							Permissions: []string{
								"admin:tenant",
								"menu:settings.ai.cost:read",
							},
						},
						{
							Key:      plugin_mgr.KeyAISettingsContextOptimizer,
							Title:    "menu.aiSettingsContextOptimizer",
							Icon:     "i-heroicons-adjustments-horizontal",
							URL:      "/settings/ai/context-optimizer",
							Order:    3,
							Visible:  true,
							Origin:   plugin_mgr.OriginSystem,
							ParentID: plugin_mgr.KeyAISettings,
							Permissions: []string{
								"admin:tenant",
								"menu:settings.ai.context_optimizer:read",
							},
						},
						{
							Key:      plugin_mgr.KeyAISettingsAgentAccess,
							Title:    "menu.aiSettingsAgentAccess",
							Icon:     "i-heroicons-shield-check",
							URL:      "/settings/ai/agent-access-grants",
							Order:    4,
							Visible:  true,
							Origin:   plugin_mgr.OriginSystem,
							ParentID: plugin_mgr.KeyAISettings,
							Permissions: []string{
								"admin:tenant",
								"menu:agent.management:read",
							},
						},
					},
				},
				{
					Key:      "integration_api_keys",
					Title:    "menu.integrationApiKeys",
					Icon:     "i-heroicons-key",
					URL:      "/settings/integration-api-keys",
					Order:    6,
					Visible:  true,
					Origin:   plugin_mgr.OriginSystem,
					ParentID: plugin_mgr.KeySettings,
					Permissions: []string{
						"menu:settings.integration_api_keys:read",
					},
				},
				{
					Key:      "open_capabilities",
					Title:    "menu.openCapabilities",
					Icon:     "i-heroicons-bolt",
					URL:      "/settings/open-capabilities",
					Order:    7,
					Visible:  true,
					Origin:   plugin_mgr.OriginSystem,
					ParentID: plugin_mgr.KeySettings,
					Permissions: []string{
						"admin:tenant",
						"menu:settings.open_capabilities:read",
					},
				},
				{
					Key:      "event_fabric",
					Title:    "menu.eventFabric",
					Icon:     "i-heroicons-queue-list",
					URL:      "/settings/event-fabric",
					Order:    8,
					Visible:  true,
					Origin:   plugin_mgr.OriginSystem,
					ParentID: plugin_mgr.KeySettings,
					Permissions: []string{
						"admin:tenant",
						"menu:settings.event_fabric:read",
					},
				},
			},
		},
	}
}
