// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	adminauth "PowerX/internal/handler/admin/auth"
	adminbusinessopportunity "PowerX/internal/handler/admin/business/opportunity"
	admincommon "PowerX/internal/handler/admin/common"
	admincontractway "PowerX/internal/handler/admin/contractway"
	admincustomerdomaincustomer "PowerX/internal/handler/admin/customerdomain/customer"
	admincustomerdomainleader "PowerX/internal/handler/admin/customerdomain/leader"
	admindepartment "PowerX/internal/handler/admin/department"
	admindictionary "PowerX/internal/handler/admin/dictionary"
	adminemployee "PowerX/internal/handler/admin/employee"
	adminmarketmedia "PowerX/internal/handler/admin/market/media"
	adminmarketstore "PowerX/internal/handler/admin/market/store"
	adminmediaresource "PowerX/internal/handler/admin/mediaresource"
	adminpermission "PowerX/internal/handler/admin/permission"
	adminposition "PowerX/internal/handler/admin/position"
	adminproduct "PowerX/internal/handler/admin/product"
	adminproductartisan "PowerX/internal/handler/admin/product/artisan"
	adminproductcategory "PowerX/internal/handler/admin/product/category"
	adminproductpricebook "PowerX/internal/handler/admin/product/pricebook"
	adminproductpricebookentry "PowerX/internal/handler/admin/product/pricebookentry"
	adminproductproductspecific "PowerX/internal/handler/admin/product/productspecific"
	adminproductsku "PowerX/internal/handler/admin/product/sku"
	adminscrmapp "PowerX/internal/handler/admin/scrm/app"
	adminscrmbot "PowerX/internal/handler/admin/scrm/bot"
	adminscrmcustomer "PowerX/internal/handler/admin/scrm/customer"
	adminscrmorganization "PowerX/internal/handler/admin/scrm/organization"
	adminscrmqrcode "PowerX/internal/handler/admin/scrm/qrcode"
	adminscrmresource "PowerX/internal/handler/admin/scrm/resource"
	adminscrmtag "PowerX/internal/handler/admin/scrm/tag"
	admintradeaddressbilling "PowerX/internal/handler/admin/trade/address/billing"
	admintradeaddressdelivery "PowerX/internal/handler/admin/trade/address/delivery"
	admintradeaddressshipping "PowerX/internal/handler/admin/trade/address/shipping"
	admintradeorder "PowerX/internal/handler/admin/trade/order"
	admintradepayment "PowerX/internal/handler/admin/trade/payment"
	admintradetoken "PowerX/internal/handler/admin/trade/token"
	admintradewarehouse "PowerX/internal/handler/admin/trade/warehouse"
	adminuserinfo "PowerX/internal/handler/admin/userinfo"
	mpcustomerauth "PowerX/internal/handler/mp/customer/auth"
	mpdictionary "PowerX/internal/handler/mp/dictionary"
	mpmarketmedia "PowerX/internal/handler/mp/market/media"
	mpmarketstore "PowerX/internal/handler/mp/market/store"
	mpproduct "PowerX/internal/handler/mp/product"
	mpproductartisan "PowerX/internal/handler/mp/product/artisan"
	mptradeaddressbilling "PowerX/internal/handler/mp/trade/address/billing"
	mptradeaddressdelivery "PowerX/internal/handler/mp/trade/address/delivery"
	mptradeaddressshipping "PowerX/internal/handler/mp/trade/address/shipping"
	mptradecart "PowerX/internal/handler/mp/trade/cart"
	mptradeorder "PowerX/internal/handler/mp/trade/order"
	mptradepayment "PowerX/internal/handler/mp/trade/payment"
	webcustomerauth "PowerX/internal/handler/web/customer/auth"
	webcustomerauthoa "PowerX/internal/handler/web/customer/auth/oa"
	webscene "PowerX/internal/handler/web/scene"
	"PowerX/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: GetHomeHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeNoPermJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/options/employees",
					Handler: admincommon.GetEmployeeOptionsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/options/employee-query",
					Handler: admincommon.GetEmployeeQueryOptionsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/options/departments",
					Handler: admincommon.GetDepartmentOptionsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/options",
					Handler: admincommon.GetOptionsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/common"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/department-tree/:depId",
					Handler: admindepartment.GetDepartmentTreeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/departments/:id",
					Handler: admindepartment.GetDepartmentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/departments",
					Handler: admindepartment.CreateDepartmentHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/departments/:id",
					Handler: admindepartment.PatchDepartmentHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/departments/:id",
					Handler: admindepartment.DeleteDepartmentHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/department"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/positions",
					Handler: adminposition.CreatePositionHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/positions/:id",
					Handler: adminposition.PatchPositionHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/positions/:id",
					Handler: adminposition.DeletePositionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/positions",
					Handler: adminposition.ListPositionsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/positions/:id",
					Handler: adminposition.GetPositionHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/position"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/employees/actions/sync",
					Handler: adminemployee.SyncEmployeesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/employees/:id",
					Handler: adminemployee.GetEmployeeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/employees",
					Handler: adminemployee.ListEmployeesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/employees",
					Handler: adminemployee.CreateEmployeeHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/employees/:id",
					Handler: adminemployee.UpdateEmployeeHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/employees/:id",
					Handler: adminemployee.DeleteEmployeeHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/employees/actions/reset-password",
					Handler: adminemployee.ResetPasswordHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/employee"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/roles",
					Handler: adminpermission.ListRolesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/roles",
					Handler: adminpermission.CreateRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/roles/:roleCode",
					Handler: adminpermission.GetRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/roles/:roleCode",
					Handler: adminpermission.PatchRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/roles/:roleCode/users",
					Handler: adminpermission.GetRoleEmployeesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/roles/:roleCode/actions/set-permissions",
					Handler: adminpermission.SetRolePermissionsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api-list",
					Handler: adminpermission.ListAPIHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/roles/:roleCode/actions/set-employees",
					Handler: adminpermission.SetRoleEmployeesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/users/:userId/actions/set-roles",
					Handler: adminpermission.SetUserRolesHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/permission"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/access/actions/basic-login",
				Handler: adminauth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/access/actions/exchange-token",
				Handler: adminauth.ExchangeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/types/page-list",
					Handler: admindictionary.ListDictionaryPageTypesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/types",
					Handler: admindictionary.ListDictionaryTypesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/types/:type",
					Handler: admindictionary.GetDictionaryTypeHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/types",
					Handler: admindictionary.CreateDictionaryTypeHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/types/:type",
					Handler: admindictionary.UpdateDictionaryTypeHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/types/:type",
					Handler: admindictionary.DeleteDictionaryTypeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/items",
					Handler: admindictionary.ListDictionaryItemsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/items/:type/:key",
					Handler: admindictionary.GetDictionaryItemHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/items",
					Handler: admindictionary.CreateDictionaryItemHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/items/:type/:key",
					Handler: admindictionary.UpdateDictionaryItemHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/items/:type/:key",
					Handler: admindictionary.DeleteDictionaryItemHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/dictionary"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/user-info",
					Handler: adminuserinfo.GetUserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/menu-roles",
					Handler: adminuserinfo.GetMenuRolesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/users/actions/modify-password",
					Handler: adminuserinfo.ModifyUserPasswordHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/user-center"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/leads/:id",
					Handler: admincustomerdomainleader.GetLeadHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/leads/page-list",
					Handler: admincustomerdomainleader.ListLeadsPageHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/leads",
					Handler: admincustomerdomainleader.CreateLeadHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/leads/:id",
					Handler: admincustomerdomainleader.PutLeadHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/leads/:id",
					Handler: admincustomerdomainleader.PatchLeadHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/leads/:id",
					Handler: admincustomerdomainleader.DeleteLeadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/leads/:id/actions/employees",
					Handler: admincustomerdomainleader.AssignLeadToEmployeeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/customerdomain"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/customers/:id",
					Handler: admincustomerdomaincustomer.GetCustomerHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/customers/page-list",
					Handler: admincustomerdomaincustomer.ListCustomersPageHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/customers",
					Handler: admincustomerdomaincustomer.CreateCustomerHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/customers/:id",
					Handler: admincustomerdomaincustomer.PutCustomerHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/customers/:id",
					Handler: admincustomerdomaincustomer.PatchCustomerHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/customers/:id",
					Handler: admincustomerdomaincustomer.DeleteCustomerHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/customers/:id/actions/employees",
					Handler: admincustomerdomaincustomer.AssignCustomerToEmployeeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/customerdomain"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/medias/page-list",
					Handler: adminmarketmedia.ListMediasPageHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/medias",
					Handler: adminmarketmedia.CreateMediaHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/medias/:id",
					Handler: adminmarketmedia.UpdateMediaHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/medias/:id",
					Handler: adminmarketmedia.GetMediaHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/medias/:id",
					Handler: adminmarketmedia.DeleteMediaHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/market"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/stores/page-list",
					Handler: adminmarketstore.ListStoresPageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/stores/:id",
					Handler: adminmarketstore.GetStoreHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/stores",
					Handler: adminmarketstore.CreateStoreHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/stores/:id",
					Handler: adminmarketstore.PutStoreHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/stores/:id",
					Handler: adminmarketstore.DeleteStoreHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/stores/:id/actions/assign-to-store-categroy",
					Handler: adminmarketstore.AssignStoreToStoreManagerHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/market"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/opportunities",
					Handler: adminbusinessopportunity.GetOpportunityListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/opportunities",
					Handler: adminbusinessopportunity.CreateOpportunityHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/opportunities/:id/assign-employee",
					Handler: adminbusinessopportunity.AssignEmployeeToOpportunityHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/opportunities/:id",
					Handler: adminbusinessopportunity.UpdateOpportunityHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/opportunities/:id",
					Handler: adminbusinessopportunity.DeleteOpportunityHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/business"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/price-books/page-list",
					Handler: adminproductpricebook.ListPriceBooksHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/price-books/:id",
					Handler: adminproductpricebook.GetPriceBookHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/price-books",
					Handler: adminproductpricebook.UpsertPriceBookHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/price-books/:id",
					Handler: adminproductpricebook.DeletePriceBookHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/product"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/products/page-list",
					Handler: adminproduct.ListProductsPageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/products/:id",
					Handler: adminproduct.GetProductHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/products",
					Handler: adminproduct.CreateProductHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/products/:id",
					Handler: adminproduct.PutProductHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/products/:id",
					Handler: adminproduct.PatchProductHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/products/:id",
					Handler: adminproduct.DeleteProductHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/products/:id/actions/assign-to-product-categroy",
					Handler: adminproduct.AssignProductToProductCategoryHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/product"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/resources/page-list",
					Handler: adminmediaresource.ListMediaResourcesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/resources",
					Handler: adminmediaresource.CreateMediaResourceHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/resources/base64",
					Handler: adminmediaresource.CreateMediaResourceByBase64Handler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/resources/:id",
					Handler: adminmediaresource.GetMediaResourceHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/resources/:id",
					Handler: adminmediaresource.DeleteMediaResourceHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/media"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/product-category-tree",
					Handler: adminproductcategory.ListProductCategoryTreeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/product-categories/:id",
					Handler: adminproductcategory.GetProductCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/product-categories",
					Handler: adminproductcategory.CreateProductCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/product-categories/:id",
					Handler: adminproductcategory.UpdateProductCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/product-categories/:id",
					Handler: adminproductcategory.PatchProductCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/product-categories/:id",
					Handler: adminproductcategory.DeleteProductCategoryHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/product"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/product-specifics/page-list",
					Handler: adminproductproductspecific.ListProductSpecificPageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/product-specifics/:id",
					Handler: adminproductproductspecific.GetProductSpecificHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/product-specifics",
					Handler: adminproductproductspecific.CreateProductSpecificHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/product-specifics/config",
					Handler: adminproductproductspecific.ConfigProductSpecificHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/product-specifics/:id",
					Handler: adminproductproductspecific.PutProductSpecificHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/product-specifics/:id",
					Handler: adminproductproductspecific.PatchProductSpecificHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/product-specifics/:id",
					Handler: adminproductproductspecific.DeleteProductSpecificHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/product"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/skus/page-list",
					Handler: adminproductsku.ListSKUPageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/skus/:id",
					Handler: adminproductsku.GetSKUHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/skus",
					Handler: adminproductsku.CreateSKUHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/skus/config",
					Handler: adminproductsku.ConfigSKUHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/skus/:id",
					Handler: adminproductsku.PutSKUHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/skus/:id",
					Handler: adminproductsku.PatchSKUHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/skus/:id",
					Handler: adminproductsku.DeleteSKUHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/product"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/price-book-entries/page-list",
					Handler: adminproductpricebookentry.ListPriceBookEntriesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/price-book-entries/:id",
					Handler: adminproductpricebookentry.GetPriceBookEntryHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/price-book-entries/config",
					Handler: adminproductpricebookentry.ConfigPriceBookEntryHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/price-book-entries/:id",
					Handler: adminproductpricebookentry.UpdatePriceBookEntryHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/price-book-entries/:id",
					Handler: adminproductpricebookentry.DeletePriceBookEntryHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/product"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/artisans/page-list",
					Handler: adminproductartisan.ListArtisansPageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/artisans/:id",
					Handler: adminproductartisan.GetArtisanHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/artisans",
					Handler: adminproductartisan.CreateArtisanHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/artisans/:id",
					Handler: adminproductartisan.PutArtisanHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/artisans/:id",
					Handler: adminproductartisan.DeleteArtisanHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/product"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/products/page-list",
					Handler: admintradetoken.ListTokenProductsPageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/products/:id",
					Handler: admintradetoken.GetTokenProductHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/products",
					Handler: admintradetoken.CreateTokenProductHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/products/:id",
					Handler: admintradetoken.PutTokenProductHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/products/:id",
					Handler: admintradetoken.PatchTokenProductHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/products/:id",
					Handler: admintradetoken.DeleteTokenProductHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/trade/token"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/shipping/page-list",
					Handler: admintradeaddressshipping.ListShippingAddressesPageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/shipping/:id",
					Handler: admintradeaddressshipping.GetShippingAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/shipping",
					Handler: admintradeaddressshipping.CreateShippingAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/shipping/:id",
					Handler: admintradeaddressshipping.PutShippingAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/shipping/:id",
					Handler: admintradeaddressshipping.PatchShippingAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/shipping/:id",
					Handler: admintradeaddressshipping.DeleteShippingAddressHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/trade/address"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/billing/page-list",
					Handler: admintradeaddressbilling.ListBillingAddressesPageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/billing/:id",
					Handler: admintradeaddressbilling.GetBillingAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/billing",
					Handler: admintradeaddressbilling.CreateBillingAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/billing/:id",
					Handler: admintradeaddressbilling.PutBillingAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/billing/:id",
					Handler: admintradeaddressbilling.PatchBillingAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/billing/:id",
					Handler: admintradeaddressbilling.DeleteBillingAddressHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/trade/address"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/delivery/page-list",
					Handler: admintradeaddressdelivery.ListDeliveryAddressesPageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/delivery/:id",
					Handler: admintradeaddressdelivery.GetDeliveryAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/delivery",
					Handler: admintradeaddressdelivery.CreateDeliveryAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/delivery/:id",
					Handler: admintradeaddressdelivery.PutDeliveryAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/delivery/:id",
					Handler: admintradeaddressdelivery.PatchDeliveryAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/delivery/:id",
					Handler: admintradeaddressdelivery.DeleteDeliveryAddressHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/trade/address"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/warehouses",
					Handler: admintradewarehouse.ListWarehousesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/warehouses/:id",
					Handler: admintradewarehouse.GetWarehouseHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/warehouses",
					Handler: admintradewarehouse.CreateWarehouseHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/warehouses/:id",
					Handler: admintradewarehouse.UpdateWarehouseHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/warehouses/:id",
					Handler: admintradewarehouse.PatchWarehouseHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/warehouses/:id",
					Handler: admintradewarehouse.DeleteWarehouseHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/trade"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/group-tree",
					Handler: admincontractway.GetContractWayGroupTreeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/groups",
					Handler: admincontractway.GetContractWayGroupListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: admincontractway.GetContractWaysHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: admincontractway.CreateContractWayHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: admincontractway.UpdateContractWayHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: admincontractway.DeleteContractWayHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/contract-way"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/employee/page",
					Handler: adminscrmorganization.ListWeWorkEmployeePageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/sync",
					Handler: adminscrmorganization.SyncWeWorkEmployeeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/scrm/organization/wechat"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/partment/page",
					Handler: adminscrmorganization.ListWeWorkDepartMentPageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/scrm/organization/wechat"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/group/list",
					Handler: adminscrmapp.ListWeWorkAppGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/group/create",
					Handler: adminscrmapp.CreateWeWorkAppGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/group/message/articles",
					Handler: adminscrmapp.SendWeWorkAppGroupArticleMessageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/scrm/app/wechat"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/detail",
					Handler: adminscrmapp.DetailWeWorkAppHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/options",
					Handler: adminscrmapp.ListWeWorkAppOptionHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/scrm/app/wechat"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/message/articles",
					Handler: adminscrmapp.SendWeWorkAppArticleMessageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/scrm/app/wechat"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/sync",
					Handler: adminscrmcustomer.SyncWeWorkCustomerOptionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/page",
					Handler: adminscrmcustomer.ListWeWorkCustomerPageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/scrm/customer/wechat"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/group/list",
					Handler: adminscrmcustomer.ListWeWorkCustomerGroupLimitHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/group/message/template",
					Handler: adminscrmcustomer.SendWeWorkCustomerGroupMessageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/scrm/customer/wechat"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/message/articles",
					Handler: adminscrmbot.BotWeWorkArticlesHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/scrm/bot/wechat"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/image/upload",
					Handler: adminscrmresource.CreateWeWorkImageHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/image/page",
					Handler: adminscrmresource.ListWeWorkImageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/scrm/resource/wechat"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/group/page",
					Handler: adminscrmqrcode.ListWeWorkQrcodePageHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/group/create",
					Handler: adminscrmqrcode.CreateWeWorkQrcodeHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/group/update/:qid",
					Handler: adminscrmqrcode.UpdateWeWorkQrcodeHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/group/enable/:qid",
					Handler: adminscrmqrcode.EnableWeWorkQrcodeHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/group/disable/:qid",
					Handler: adminscrmqrcode.DisableWeWorkQrcodeHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/group/:qid",
					Handler: adminscrmqrcode.DeleteWeWorkQrcodeHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/qrcode/:qid",
					Handler: adminscrmqrcode.UpdateActiveQrcodeLinkHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/scrm/qrcode/wechat"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/group/option",
					Handler: adminscrmtag.ListWeWorkTagGroupOptionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/group/page",
					Handler: adminscrmtag.ListWeWorkTagGroupPageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/corp/option",
					Handler: adminscrmtag.ListWeWorkTagOptionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/group/action",
					Handler: adminscrmtag.ActionWeWorkCropTagGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/corp/page",
					Handler: adminscrmtag.ListWeWorkTagPageHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/sync",
					Handler: adminscrmtag.SyncWeWorkGroupTagHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/crop/create",
					Handler: adminscrmtag.CreateWeWorkCropTagHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/crop/update",
					Handler: adminscrmtag.UpdateWeWorkCropTagHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/crop/delete",
					Handler: adminscrmtag.DeleteWeWorkCropTagHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/customer/action",
					Handler: adminscrmtag.ActionWeWorkCustomerTagHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/scrm/tag/wechat"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.MPCustomerJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/types/page-list",
					Handler: mpdictionary.ListDictionaryPageTypesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/types/:type",
					Handler: mpdictionary.GetDictionaryTypeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/items",
					Handler: mpdictionary.ListDictionaryItemsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/items/:type/:key",
					Handler: mpdictionary.GetDictionaryItemHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/mp/dictionary"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: mpcustomerauth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/authByPhone",
				Handler: mpcustomerauth.AuthByPhoneHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/authByProfile",
				Handler: mpcustomerauth.AuthByProfileHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/mp/customer"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.MPCustomerJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/stores/page-list",
					Handler: mpmarketstore.ListStoresPageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/mp/market"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.MPCustomerJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/medias/page-list",
					Handler: mpmarketmedia.ListMediasPageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/mp/market"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.MPCustomerJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/artisans/page-list",
					Handler: mpproductartisan.ListArtisansPageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/artisans/:id",
					Handler: mpproductartisan.GetArtisanHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/mp/product"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.MPCustomerJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/products/page-list",
					Handler: mpproduct.ListProductsPageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/products/:id",
					Handler: mpproduct.GetProductHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/mp/product"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.MPCustomerJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/product-category-tree",
					Handler: mpproduct.ListProductCategoryTreeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/product-categories",
					Handler: mpproduct.ListProductCategoriesHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/mp/product"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.MPCustomerJWTAuth, serverCtx.MPCustomerGet},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/cart/items/page-list",
					Handler: mptradecart.ListCartItemsPageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/cart/:cartId",
					Handler: mptradecart.GetCartHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/cart/items",
					Handler: mptradecart.AddToCartHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/cart/items/:itemId",
					Handler: mptradecart.UpdateCartItemQuantityHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/cart/items/:itemId",
					Handler: mptradecart.RemoveCartItemHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/cart/items/clear",
					Handler: mptradecart.ClearCartItemsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/mp/trade"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.MPCustomerJWTAuth, serverCtx.MPCustomerGet},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/orders/page-list",
					Handler: mptradeorder.ListOrdersPageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/orders/:id",
					Handler: mptradeorder.GetOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/orders/products",
					Handler: mptradeorder.CreateOrderByProductsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/orders/cart-items",
					Handler: mptradeorder.CreateOrderByCartItemsHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/orders/cancel/:id",
					Handler: mptradeorder.CancelOrderHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/mp/trade"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/orders/page-list",
					Handler: admintradeorder.ListOrdersPageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/orders/:id",
					Handler: admintradeorder.GetOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/orders",
					Handler: admintradeorder.CreateOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/orders/:id",
					Handler: admintradeorder.PutOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/orders/:id",
					Handler: admintradeorder.PatchOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/orders/:id",
					Handler: admintradeorder.DeleteOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/orders/export",
					Handler: admintradeorder.ExportOrdersHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/trade"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EmployeeJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/payments/page-list",
					Handler: admintradepayment.ListPaymentsPageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/payments/:id",
					Handler: admintradepayment.GetPaymentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/payments",
					Handler: admintradepayment.CreatePaymentHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/payments/:id",
					Handler: admintradepayment.PutPaymentHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/payments/:id",
					Handler: admintradepayment.PatchPaymentHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/payments/:id",
					Handler: admintradepayment.DeletePaymentHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin/trade"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.MPCustomerJWTAuth, serverCtx.MPCustomerGet},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/shipping/page-list",
					Handler: mptradeaddressshipping.ListShippingAddressesPageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/shipping/:id",
					Handler: mptradeaddressshipping.GetShippingAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/shipping",
					Handler: mptradeaddressshipping.CreateShippingAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/shipping/:id",
					Handler: mptradeaddressshipping.PutShippingAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/shipping/:id",
					Handler: mptradeaddressshipping.PatchShippingAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/shipping/:id",
					Handler: mptradeaddressshipping.DeleteShippingAddressHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/mp/trade/address"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.MPCustomerJWTAuth, serverCtx.MPCustomerGet},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/delivery/page-list",
					Handler: mptradeaddressdelivery.ListDeliveryAddressesPageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/delivery/:id",
					Handler: mptradeaddressdelivery.GetDeliveryAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/delivery",
					Handler: mptradeaddressdelivery.CreateDeliveryAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/delivery/:id",
					Handler: mptradeaddressdelivery.PutDeliveryAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/delivery/:id",
					Handler: mptradeaddressdelivery.PatchDeliveryAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/delivery/:id",
					Handler: mptradeaddressdelivery.DeleteDeliveryAddressHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/mp/trade/address"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.MPCustomerJWTAuth, serverCtx.MPCustomerGet},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/billing/page-list",
					Handler: mptradeaddressbilling.ListBillingAddressesPageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/billing/:id",
					Handler: mptradeaddressbilling.GetBillingAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/billing",
					Handler: mptradeaddressbilling.CreateBillingAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/billing/:id",
					Handler: mptradeaddressbilling.PutBillingAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/billing/:id",
					Handler: mptradeaddressbilling.PatchBillingAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/billing/:id",
					Handler: mptradeaddressbilling.DeleteBillingAddressHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/mp/trade/address"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.MPCustomerJWTAuth, serverCtx.MPCustomerGet},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/payments/page-list",
					Handler: mptradepayment.ListPaymentsPageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/payments/:id",
					Handler: mptradepayment.GetPaymentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/payments",
					Handler: mptradepayment.CreatePaymentFromOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/payments/:id",
					Handler: mptradepayment.UpdatePaymentHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/mp/trade"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.WebCustomerJWTAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/types/page-list",
					Handler: mpdictionary.ListDictionaryPageTypesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/types/:type",
					Handler: mpdictionary.GetDictionaryTypeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/items",
					Handler: mpdictionary.ListDictionaryItemsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/items/:type/:key",
					Handler: mpdictionary.GetDictionaryItemHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/web/dictionary"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: webcustomerauth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/registerByPhone",
				Handler: webcustomerauth.RegisterCustomerByPhoneHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/updateCustomerProfile/:id",
				Handler: webcustomerauth.UpdateCustomerProfileHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/web/customer"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/oa/login",
				Handler: webcustomerauthoa.OALoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/oa/authByPhone",
				Handler: webcustomerauthoa.AuthByPhoneHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/oa/authByProfile",
				Handler: webcustomerauthoa.AuthByProfileHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/web/customer"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/qrcode/detail/:qid",
				Handler: webscene.DetailQrcodeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/web/scene"),
	)
}
