package model

var PowerXSchema = "public"

const TableAgentPlanRun = "agent_plan_runs"
const TableAgentEvent = "agent_task_events"

const TableMediaAsset = "media_assets"

const TableIAMTenant = "iam_tenant"
const TableTenantKeyPair = "iam_tenant_key_pairs"
const TableIAMUser = "iam_user"
const TableIAMMember = "iam_member"
const TableIAMCredential = "iam_credential"
const TableIAMRole = "iam_role"
const TableIAMPermission = "iam_permission"
const TableIAMRolePermission = "iam_role_permission"
const TableIAMRefreshToken = "iam_refresh_token"
const TableIAMDepartment = "iam_department"
const TableIAMMemberDepartment = "iam_member_department"
const TableIAMDepartmentClosure = "iam_department_closure"
const TableIAMMemberAssignment = "iam_member_assignment"
const TableIAMTeam = "iam_team"
const TableIAMPosition = "iam_position"
const TableIAMGroup = "iam_group"
const TableIAMRoleBinding = "iam_role_binding"
const TableIAMServiceAccount = "iam_service_account"
const TableIAMAPIKey = "iam_api_key"

const TableAuditEvent = "audit_event"

const TableCapabilityContract = "capability_contracts"
const TableCapabilityIOSchema = "capability_io_schemas"
const TableCapabilityVersionPolicy = "capability_version_policies"
const TableCapabilityTransportProfile = "capability_transport_profiles"
const TableCapabilityErrorTaxonomy = "capability_error_taxonomies"
const TableCapabilityContractErrorTaxonomy = "capability_contract_error_taxonomies"

const TableCapabilityRegistryRegistration = "capability_registry_registrations"
const TableCapabilityRegistryAdapterEndpoint = "capability_registry_adapter_endpoints"
const TableCapabilityRegistryRoutingPolicy = "capability_registry_routing_policies"
const TableCapabilityRegistryFallbackPlan = "capability_registry_fallback_plans"
const TableCapabilityRegistryHealthProbeResult = "capability_registry_health_probe_results"
const TableCapabilityRegistryDiscoveryCache = "capability_registry_discovery_cache"

const TableEventTopics = "event_topics"
const TableEventAclBindings = "event_acl_bindings"
const TableEventEnvelopes = "event_envelopes"
const TableEventDeliveryAttempts = "event_delivery_attempts"
const TableEventDlqMessages = "event_dlq_messages"
const TableEventSubscriptionOffsets = "event_subscription_offsets"
