<script setup lang="ts">
import { useCustomerService, type CustomerAccount, type CustomerAuthIdentity, type CustomerContact, type CustomerLoginEvent, type CustomerMembership, type MiniAppEntry, type ContactIdentity } from '~/composables/api/services/customerService'
definePageMeta({ title: 'customers', icon: 'i-heroicons-users' })
const { t } = useI18n(); const route = useRoute(); const api = useCustomerService()
const customerUUID = computed(() => String(route.params.customer_uuid || '').trim())
const activeTab = ref<'basic' | 'identities' | 'memberships' | 'events' | 'entries' | 'contacts'>('basic')
const loading = ref(false), error = ref(''), account = ref<CustomerAccount | null>(null)
const identities = ref<CustomerAuthIdentity[]>([]), memberships = ref<CustomerMembership[]>([]), loginEvents = ref<CustomerLoginEvent[]>([]), entries = ref<MiniAppEntry[]>([]), contacts = ref<CustomerContact[]>([])
const selectedContact = ref<CustomerContact | null>(null), contactIdentities = ref<ContactIdentity[]>([]), contactModalOpen = ref(false), identityModalOpen = ref(false), saving = ref(false), actionError = ref('')
const contactForm = reactive({ display_name: '', given_name: '', family_name: '', primary: false, legal: false, tags: '' })
const identityForm = reactive({ channel: '', external_subject: '' })
const resolveResult = ref<any>(null)
const tabs = computed(() => [{ id: 'basic', label: t('customerMaster.basic') }, { id: 'identities', label: t('customerMaster.authIdentities') }, { id: 'memberships', label: t('customerMaster.memberships') }, { id: 'events', label: t('customerMaster.loginEvents') }, { id: 'entries', label: t('customerMaster.miniAppEntries') }, { id: 'contacts', label: t('customerMaster.contacts') }])
const formatTime = (value?: string) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '-'
const short = (value?: string) => value && value.length > 20 ? `${value.slice(0, 8)}…${value.slice(-4)}` : value || '-'
async function load() { if (!customerUUID.value) return; loading.value = true; error.value = ''; try { const [customer, auth, member, events, miniApp, contactPage] = await Promise.all([api.get(customerUUID.value), api.listAuthIdentities(customerUUID.value), api.listMemberships(customerUUID.value), api.listLoginEvents(customerUUID.value), api.listMiniAppEntries(), api.listContacts(customerUUID.value)]); account.value = customer; identities.value = auth.items; memberships.value = member.items; loginEvents.value = events.items; entries.value = miniApp.items; contacts.value = contactPage.items } catch (cause: any) { error.value = cause?.data?.error?.message || cause?.message || t('customerMaster.loadFailed') } finally { loading.value = false } }
function resetContactForm(contact?: CustomerContact) { selectedContact.value = contact || null; actionError.value = ''; contactForm.display_name = contact?.display_name || ''; contactForm.given_name = contact?.given_name || ''; contactForm.family_name = contact?.family_name || ''; contactForm.primary = Boolean(contact?.roles?.includes('primary')); contactForm.legal = Boolean(contact?.roles?.includes('legal_representative')); contactForm.tags = contact?.tags?.join(', ') || ''; contactModalOpen.value = true }
async function saveContact(temporary = false) { if (!contactForm.display_name.trim()) { actionError.value = t('customerMaster.saveFailed'); return }; saving.value = true; actionError.value = ''; const roles = [contactForm.primary ? 'primary' : '', contactForm.legal ? 'legal_representative' : ''].filter(Boolean); const tags = contactForm.tags.split(',').map(v => v.trim()).filter(Boolean); try { if (selectedContact.value) await api.updateContact(customerUUID.value, selectedContact.value.uuid, { display_name: contactForm.display_name.trim(), given_name: contactForm.given_name.trim() || undefined, family_name: contactForm.family_name.trim() || undefined, roles, tags }); else await api.createContact(customerUUID.value, { display_name: contactForm.display_name.trim(), given_name: contactForm.given_name.trim() || undefined, family_name: contactForm.family_name.trim() || undefined, status: temporary ? 'temporary' : 'active', roles, tags, creation_intent: temporary ? 'explicit_temporary' : 'explicit_create' }); contacts.value = (await api.listContacts(customerUUID.value)).items; contactModalOpen.value = false } catch (cause: any) { actionError.value = cause?.data?.error?.message || cause?.message || t('customerMaster.saveFailed') } finally { saving.value = false } }
async function deactivate(contact: CustomerContact) { saving.value = true; try { await api.updateContact(customerUUID.value, contact.uuid, { status: 'inactive' }); contacts.value = (await api.listContacts(customerUUID.value)).items } catch (cause: any) { actionError.value = cause?.data?.error?.message || cause?.message || t('customerMaster.saveFailed') } finally { saving.value = false } }
async function openIdentities(contact: CustomerContact) { selectedContact.value = contact; actionError.value = ''; try { contactIdentities.value = (await api.listContactIdentities(customerUUID.value, contact.uuid)).items; identityModalOpen.value = true } catch (cause: any) { actionError.value = cause?.data?.error?.message || cause?.message || t('customerMaster.loadFailed') } }
async function bindIdentity() { if (!selectedContact.value || !identityForm.channel.trim() || !identityForm.external_subject.trim()) return; saving.value = true; actionError.value = ''; try { await api.bindContactIdentity(customerUUID.value, selectedContact.value.uuid, identityForm.channel.trim(), identityForm.external_subject.trim()); contactIdentities.value = (await api.listContactIdentities(customerUUID.value, selectedContact.value.uuid)).items; identityForm.channel = ''; identityForm.external_subject = '' } catch (cause: any) { actionError.value = cause?.data?.error?.message || cause?.message || t('customerMaster.identityConflict') } finally { saving.value = false } }
async function resolveIdentity() { if (!identityForm.channel.trim() || !identityForm.external_subject.trim()) return; saving.value = true; actionError.value = ''; resolveResult.value = null; try { resolveResult.value = await api.resolveContactIdentity(customerUUID.value, identityForm.channel.trim(), identityForm.external_subject.trim()) } catch (cause: any) { actionError.value = cause?.data?.error?.message || cause?.message || t('customerMaster.resolveNotFound') } finally { saving.value = false } }
onMounted(load)
</script>

<template>
  <div class="space-y-6 p-6">
    <div class="flex flex-wrap items-start justify-between gap-3"><div><UButton variant="link" icon="i-heroicons-arrow-left" to="/customers">{{ t('customerMaster.back') }}</UButton><h1 class="mt-2 text-2xl font-bold text-gray-900 dark:text-white">{{ account?.display_name || account?.nickname || t('customerMaster.customer') }}</h1><p class="mt-1 font-mono text-xs text-gray-500">{{ customerUUID }}</p></div><UButton icon="i-heroicons-arrow-path" :loading="loading" @click="load">{{ t('common.refresh') }}</UButton></div>
    <UAlert v-if="error" color="error" variant="soft" :title="error" />
    <div v-else-if="account" class="rounded-lg border border-gray-200 bg-white shadow-sm dark:border-gray-800 dark:bg-[#111a2b]"><div class="flex flex-wrap gap-1 border-b border-gray-200 p-3 dark:border-gray-800"><UButton v-for="tab in tabs" :key="tab.id" size="sm" :color="activeTab === tab.id ? 'primary' : 'neutral'" :variant="activeTab === tab.id ? 'soft' : 'ghost'" @click="activeTab = tab.id as any">{{ tab.label }}</UButton></div><div class="p-5">
      <section v-if="activeTab === 'basic'" class="grid gap-4 md:grid-cols-2"><div v-for="item in [{label:t('customerMaster.customer'), value:account.display_name || account.nickname},{label:t('customerMaster.email'), value:account.primary_email},{label:t('customerMaster.phone'), value:account.primary_phone},{label:t('common.status'), value:account.status},{label:t('customerMaster.source'), value:account.member_source},{label:t('customerMaster.updatedAt'), value:formatTime(account.updated_at)}]" :key="item.label" class="rounded-md border border-gray-200 p-3 dark:border-gray-800"><p class="text-xs text-gray-500">{{ item.label }}</p><p class="mt-1 break-all text-sm font-medium text-gray-900 dark:text-white">{{ item.value || '-' }}</p></div></section>
      <section v-else-if="activeTab === 'identities'" class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead><tr><th>{{ t('customerMaster.provider') }}</th><th>{{ t('customerMaster.subject') }}</th><th>{{ t('common.status') }}</th></tr></thead><tbody><tr v-for="identity in identities" :key="identity.uuid"><td>{{ identity.provider }}</td><td class="font-mono text-xs">{{ identity.provider_subject || identity.email || identity.phone || '-' }}</td><td>{{ identity.status }}</td></tr></tbody></table></section>
      <section v-else-if="activeTab === 'memberships'" class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead><tr><th>{{ t('customerMaster.customerUuid') }}</th><th>{{ t('customerMaster.source') }}</th><th>{{ t('common.status') }}</th><th>{{ t('customerMaster.expiresAt') }}</th></tr></thead><tbody><tr v-for="membership in memberships" :key="membership.uuid"><td class="font-mono text-xs">{{ short(membership.tenant_uuid) }}</td><td>{{ membership.source }}</td><td>{{ membership.status }}</td><td>{{ formatTime(membership.expires_at) }}</td></tr></tbody></table></section>
      <section v-else-if="activeTab === 'events'" class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead><tr><th>{{ t('customerMaster.provider') }}</th><th>{{ t('customerMaster.event') }}</th><th>{{ t('customerMaster.result') }}</th><th>{{ t('customerMaster.updatedAt') }}</th></tr></thead><tbody><tr v-for="event in loginEvents" :key="event.id"><td>{{ event.identity_provider || '-' }}</td><td>{{ event.event_type }}</td><td>{{ event.ok ? t('customerMaster.loginSuccess') : t('customerMaster.loginFailure') }}</td><td>{{ formatTime(event.created_at) }}</td></tr></tbody></table></section>
      <section v-else-if="activeTab === 'entries'"><UAlert color="info" variant="soft" :description="t('customerMaster.tenantEntryDescription')" class="mb-4" /><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead><tr><th>{{ t('customerMaster.entryCode') }}</th><th>{{ t('customerMaster.entryType') }}</th><th>{{ t('customerMaster.channel') }}</th><th>{{ t('common.status') }}</th></tr></thead><tbody><tr v-for="entry in entries" :key="entry.uuid"><td class="font-mono text-xs">{{ entry.entry_code }}</td><td>{{ entry.entry_type }}</td><td>{{ entry.channel || '-' }}</td><td>{{ entry.status }}</td></tr></tbody></table></div></section>
      <section v-else><div class="mb-4 flex flex-wrap justify-between gap-2"><p class="text-sm text-gray-600 dark:text-gray-300">{{ t('customerMaster.contacts') }}</p><UButton icon="i-heroicons-plus" @click="resetContactForm()">{{ t('customerMaster.createContact') }}</UButton></div><p v-if="actionError" class="mb-3 text-sm text-error-600">{{ actionError }}</p><div v-if="contacts.length === 0" class="rounded-md bg-gray-50 p-4 text-sm text-gray-500 dark:bg-slate-900">{{ t('customerMaster.contactEmpty') }}</div><div v-else class="space-y-2"><div v-for="contact in contacts" :key="contact.uuid" class="flex flex-wrap items-center justify-between gap-3 rounded-md border border-gray-200 p-3 dark:border-gray-800"><div><p class="font-medium text-gray-900 dark:text-white">{{ contact.display_name }}</p><p class="mt-1 text-xs text-gray-500">{{ contact.tags?.join(', ') || '-' }}</p></div><div class="flex flex-wrap items-center gap-2"><UBadge variant="soft">{{ contact.status }}</UBadge><UButton size="xs" variant="ghost" @click="openIdentities(contact)">{{ t('customerMaster.identity') }}</UButton><UButton size="xs" variant="ghost" @click="resetContactForm(contact)">{{ t('customerMaster.edit') }}</UButton><UButton v-if="contact.status !== 'inactive'" size="xs" color="error" variant="ghost" :loading="saving" @click="deactivate(contact)">{{ t('customerMaster.disable') }}</UButton></div></div></div></section>
    </div></div>
    <UModal v-model:open="contactModalOpen" :title="selectedContact ? t('customerMaster.edit') : t('customerMaster.createContact')"><template #body><div class="space-y-4"><UFormField :label="t('customerMaster.displayName')" required><UInput v-model="contactForm.display_name" /></UFormField><div class="grid grid-cols-2 gap-3"><UFormField :label="t('customerMaster.givenName')"><UInput v-model="contactForm.given_name" /></UFormField><UFormField :label="t('customerMaster.familyName')"><UInput v-model="contactForm.family_name" /></UFormField></div><UFormField :label="t('customerMaster.tags')" :help="t('customerMaster.tagsHint')"><UInput v-model="contactForm.tags" /></UFormField><label class="flex gap-2 text-sm"><input v-model="contactForm.primary" type="checkbox">{{ t('customerMaster.rolePrimary') }}</label><label class="flex gap-2 text-sm"><input v-model="contactForm.legal" type="checkbox">{{ t('customerMaster.roleLegalRepresentative') }}</label><UAlert v-if="!selectedContact" color="warning" variant="soft" :description="t('customerMaster.temporaryNotice')" /><p v-if="actionError" class="text-sm text-error-600">{{ actionError }}</p><div class="flex justify-end gap-2"><UButton variant="ghost" @click="contactModalOpen = false">{{ t('common.cancel') }}</UButton><UButton v-if="!selectedContact" variant="soft" :loading="saving" @click="saveContact(true)">{{ t('customerMaster.saveTemporary') }}</UButton><UButton :loading="saving" @click="saveContact(false)">{{ t('common.save') }}</UButton></div></div></template></UModal>
    <UModal v-model:open="identityModalOpen" :title="t('customerMaster.identity')"><template #body><div class="space-y-4"><div v-if="contactIdentities.length" class="space-y-2"><div v-for="identity in contactIdentities" :key="identity.uuid" class="rounded-md border border-gray-200 p-3 dark:border-gray-800"><p class="font-medium">{{ identity.channel }}</p><p class="font-mono text-xs text-gray-500">{{ identity.external_subject }}</p></div></div><p v-else class="text-sm text-gray-500">{{ t('customerMaster.identityEmpty') }}</p><UFormField :label="t('customerMaster.channel')"><UInput v-model="identityForm.channel" /></UFormField><UFormField :label="t('customerMaster.externalSubject')"><UInput v-model="identityForm.external_subject" /></UFormField><UAlert v-if="resolveResult" color="success" variant="soft" :description="resolveResult.contact?.display_name || resolveResult.contact_uuid || ''" /><p v-if="actionError" class="text-sm text-error-600">{{ actionError }}</p><div class="flex justify-end gap-2"><UButton variant="soft" :loading="saving" @click="resolveIdentity">{{ t('customerMaster.resolveIdentity') }}</UButton><UButton :loading="saving" @click="bindIdentity">{{ t('customerMaster.bindIdentity') }}</UButton></div></div></template></UModal>
  </div>
</template>
