server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: powerx-backend
    static_configs:
      - targets: [localhost]
        labels:
          job: powerx
          app: backend
          env: prod
          __path__: /var/log/powerx/backend/*.log
  - job_name: powerx-runner
    static_configs:
      - targets: [localhost]
        labels:
          job: powerx
          app: runner
          env: prod
          __path__: /var/log/powerx/runner/*.log
