package model

var PowerXSchema = "public"

const TableAgentPlanRun = "agent_plan_runs"
const TableAgentEvent = "agent_task_events"
const TableAgentProviderProfiles = "agent_provider_profiles"
const TableAgentRoutingPolicies = "agent_routing_policies"
const TableAgentConnectorInstances = "agent_connector_instances"
const TableAgentCostQuotaLedgers = "agent_cost_quota_ledgers"

const TableMediaAsset = "media_assets"
const TableMediaAssetVariant = "media_asset_variants"
const TableSystemNotifications = "system_notifications"

const TableIAMTenant = "iam_tenant"
const TableTenantKeyPair = "iam_tenant_key_pairs"
const TableIAMUser = "iam_user"
const TableIAMMember = "iam_member"
const TableIAMCredential = "iam_credential"
const TableIAMRole = "iam_role"
const TableIAMPermission = "iam_permission"
const TableIAMRolePermission = "iam_role_permission"
const TableIAMRefreshToken = "iam_refresh_token"
const TableIAMDepartment = "iam_department"
const TableIAMMemberDepartment = "iam_member_department"
const TableIAMDepartmentClosure = "iam_department_closure"
const TableIAMMemberAssignment = "iam_member_assignment"
const TableIAMTeam = "iam_team"
const TableIAMPosition = "iam_position"
const TableIAMGroup = "iam_group"
const TableIAMRoleBinding = "iam_role_binding"
const TableIAMAPIKeyProfile = "iam_api_key_profile"
const TableIAMAPIKeyProfilePermission = "iam_api_key_profile_permission"
const TableIAMAPIKey = "iam_api_key"
const TableIAMRootSupportSession = "iam_root_support_sessions"

const TableCustomerAccounts = "customer_accounts"
const TableCustomerAuthIdentities = "customer_auth_identities"
const TableCustomerTenantMemberships = "customer_tenant_memberships"
const TableMiniAppEntries = "mini_app_entries"
const TableCustomerSessions = "customer_sessions"
const TableCustomerLoginEvents = "customer_login_events"

const TableAuditEvent = "audit_event"

const TableCapabilityContract = "capability_contracts"
const TableCapabilityIOSchema = "capability_io_schemas"
const TableCapabilityVersionPolicy = "capability_version_policies"
const TableCapabilityTransportProfile = "capability_transport_profiles"
const TableCapabilityErrorTaxonomy = "capability_error_taxonomies"
const TableCapabilityContractErrorTaxonomy = "capability_contract_error_taxonomies"

const TableCapabilityRegistryRegistration = "capability_registry_registrations"
const TableCapabilityRegistryAdapterEndpoint = "capability_registry_adapter_endpoints"
const TableCapabilityRegistryRoutingPolicy = "capability_registry_routing_policies"
const TableCapabilityRegistryFallbackPlan = "capability_registry_fallback_plans"
const TableCapabilityRegistryHealthProbeResult = "capability_registry_health_probe_results"
const TableCapabilityRegistryDiscoveryCache = "capability_registry_discovery_cache"
const TableCapabilityRegistryCapabilityRecord = "capability_registry_records"
const TableCapabilityRegistryWorkflowTemplateRef = "capability_registry_workflow_template_refs"
const TableCapabilityRegistryWorkflowTemplateApproval = "capability_registry_workflow_template_approvals"
const TableCapabilityRegistrySyncJob = "capability_registry_sync_jobs"
const TableCapabilityRegistryInvocationTrace = "capability_registry_invocation_traces"
const TableCapabilityRegistryEventPublication = "capability_registry_event_publications"

const TableIntegrationGatewayRoute = "integration_gateway_routes"
const TableIntegrationGatewayRouteVersion = "integration_gateway_route_versions"
const TableIntegrationGatewayInvocationLog = "integration_gateway_invocation_logs"
const TableIntegrationGatewayEventPublication = "integration_gateway_event_publications"
const TableIntegrationGatewayAPIKey = "integration_gateway_api_keys"
const TableIntegrationGatewayAPIKeyPermission = "integration_gateway_api_key_permissions"
const TableIntegrationGatewayAPIKeyAuditLog = "integration_gateway_api_key_audit_logs"

// TableTopicRegistry 是 Topic 注册中心的逻辑唯一源常量。
// 过渡期物理表仍映射到 event_topics，待 T093 迁移后切换为最终表名。
const TableTopicRegistry = "event_topics"

// TableEventTopics 兼容旧命名，禁止新增使用；请改用 TableTopicRegistry。
const TableEventTopics = TableTopicRegistry
const TableEventAclBindings = "event_acl_bindings"
const TableEventTopicBindings = "event_topic_bindings"
const TableEventAclManifestBindings = "event_acl_manifest_bindings"
const TableEventEnvelopes = "event_envelopes"
const TableEventDeliveryAttempts = "event_delivery_attempts"
const TableEventDlqMessages = "event_dlq_messages"
const TableEventSubscriptionOffsets = "event_subscription_offsets"
const TableEventReplayRequests = "event_replay_requests"
const TableEventTaskHistories = "event_task_histories"
const TableEventScheduledTasks = "event_scheduled_tasks"
const TableEventScheduledTaskRuns = "event_scheduled_task_runs"
const TableSchedulerJobs = "scheduler_jobs"
const TableSchedulerJobRuns = "scheduler_job_runs"
const TableEventAuthCapabilities = "event_auth_capabilities"
const TableEventAuthGrants = "event_auth_grants"
const TableEventAuthGrantCapabilities = "event_auth_grant_capabilities"
const TableEventAuthGrantConditions = "event_auth_grant_conditions"
const TableEventAuthApprovalTickets = "event_auth_approval_tickets"
const TableEventAuthGrantTemplates = "event_auth_grant_templates"

const TableWorkflowDefinitions = "workflow_definitions"
const TableWorkflowInstances = "workflow_instances"
const TableWorkflowStepRecords = "workflow_step_records"
const TableWorkflowStepCompensations = "workflow_step_compensations"
const TableWorkflowAgentAssignments = "workflow_agent_assignments"
const TableWorkflowEvents = "workflow_events"
const TableWorkflowHumanReviewTasks = "workflow_human_review_tasks"
const TableWorkflowPackSeedRecords = "workflow_pack_seed_records"
const TableWorkflowPackInstallations = "workflow_pack_installations"

const TablePluginReleaseCandidates = "plugin_release_candidates"
const TablePluginReleasePlans = "plugin_release_plans"
const TablePluginReleaseCanaryRecords = "plugin_release_canary_records"
const TablePluginReleaseOfflinePackages = "plugin_release_offline_packages"
const TablePluginReleaseMarketplaceListings = "plugin_release_marketplace_listings"
const TablePluginReleaseLocalInstallSessions = "plugin_release_local_install_sessions"
const TablePluginImportRuns = "plugin_import_runs"
const TablePluginDebugReports = "plugin_debug_reports"
const TablePluginSandboxRuns = "plugin_sandbox_validation_runs"
const TableVersionGovernanceReports = "version_governance_reports"
const TablePluginCompatExceptions = "plugin_compat_exceptions"
const TableDevHotloadSessions = "dev_plugin_sessions"
const TableDevHotloadSessionEvents = "dev_plugin_session_events"

const TableKnowledgeSpaces = "knowledge_spaces"
const TableKnowledgePolicyTemplates = "knowledge_policy_template_versions"
const TableKnowledgeIngestionJobs = "knowledge_ingestion_jobs"
const TableKnowledgeArtifactBundles = "knowledge_artifact_bundles"
const TableKnowledgeFusionStrategies = "knowledge_fusion_strategy_versions"
const TableKnowledgeFeedbackCases = "knowledge_feedback_cases"
const TableKnowledgeIAMSyncTasks = "knowledge_iam_sync_tasks"
const TableKnowledgeAuditTrailEntries = "knowledge_audit_trail_entries"
const TableKnowledgeDeltaJobs = "knowledge_delta_jobs"
const TableKnowledgeDecayTasks = "knowledge_decay_tasks"
const TableKnowledgeTenantReleasePolicies = "knowledge_release_policies"
const TableKnowledgeTenantReleaseBatches = "knowledge_release_batches"
const TableKnowledgeIngestionProfileVersions = "knowledge_ingestion_profile_versions"
const TableKnowledgeIndexProfileVersions = "knowledge_index_profile_versions"
const TableKnowledgeRAGProfileVersions = "knowledge_rag_profile_versions"
const TableKnowledgeCorpusCheckJobs = "knowledge_corpus_check_jobs"
const TableKnowledgeSourceCredentials = "knowledge_source_credentials"
const TableKnowledgeSourceConnectorInstances = "knowledge_source_connector_instances"
const TableKnowledgeSpaceSyncJobs = "knowledge_space_sync_jobs"
const TableKnowledgeVectorIndexes = "knowledge_vector_indexes"

const TableSkillsRegistryRecords = "skills_registry_records"
const TableSkillsOfficialCatalog = "skills_official_catalog"
const TableSkillsCapabilityBindings = "skills_capability_bindings"
const TableSkillsExecutionTraces = "skills_execution_traces"
const TableSkillsLifecycleAudits = "skills_lifecycle_audits"
const TableSkillsInstallTasks = "skills_install_tasks"

const TableAgentTeams = "agent_teams"
const TableAgentTeamMembers = "agent_team_members"
const TableAgentHandoffTasks = "agent_handoff_tasks"
const TableAgentSharedContextRefs = "agent_shared_context_refs"

const TableOpsDeployReleaseRecords = "ops_deploy_release_records"
const TableOpsPluginLifecycleAudits = "ops_plugin_lifecycle_audits"
const TableOpsBackupPolicies = "ops_backup_policies"
const TableOpsBackupJobs = "ops_backup_jobs"
const TableOpsBackupArtifacts = "ops_backup_artifacts"
const TableOpsBackupAlerts = "ops_backup_alerts"
const TableOpsRestoreDrillRecords = "ops_restore_drill_records"
const TableOpsApprovalPolicyProfiles = "ops_approval_policy_profiles"
const TableOpsMigrationRunbookRecords = "ops_migration_runbook_records"
