package model

var PowerXSchema = "public"

const TableAgentPlanRun = "agent_plan_runs"
const TableAgentEvent = "agent_task_events"
const TableAgentProviderProfiles = "agent_provider_profiles"
const TableAgentRoutingPolicies = "agent_routing_policies"
const TableAgentConnectorInstances = "agent_connector_instances"
const TableAgentCostQuotaLedgers = "agent_cost_quota_ledgers"

const TableMediaAsset = "media_assets"

const TableIAMTenant = "iam_tenant"
const TableTenantKeyPair = "iam_tenant_key_pairs"
const TableIAMUser = "iam_user"
const TableIAMMember = "iam_member"
const TableIAMCredential = "iam_credential"
const TableIAMRole = "iam_role"
const TableIAMPermission = "iam_permission"
const TableIAMRolePermission = "iam_role_permission"
const TableIAMRefreshToken = "iam_refresh_token"
const TableIAMDepartment = "iam_department"
const TableIAMMemberDepartment = "iam_member_department"
const TableIAMDepartmentClosure = "iam_department_closure"
const TableIAMMemberAssignment = "iam_member_assignment"
const TableIAMTeam = "iam_team"
const TableIAMPosition = "iam_position"
const TableIAMGroup = "iam_group"
const TableIAMRoleBinding = "iam_role_binding"
const TableIAMServiceAccount = "iam_service_account"
const TableIAMAPIKey = "iam_api_key"

const TableAuditEvent = "audit_event"

const TableCapabilityContract = "capability_contracts"
const TableCapabilityIOSchema = "capability_io_schemas"
const TableCapabilityVersionPolicy = "capability_version_policies"
const TableCapabilityTransportProfile = "capability_transport_profiles"
const TableCapabilityErrorTaxonomy = "capability_error_taxonomies"
const TableCapabilityContractErrorTaxonomy = "capability_contract_error_taxonomies"

const TableCapabilityRegistryRegistration = "capability_registry_registrations"
const TableCapabilityRegistryAdapterEndpoint = "capability_registry_adapter_endpoints"
const TableCapabilityRegistryRoutingPolicy = "capability_registry_routing_policies"
const TableCapabilityRegistryFallbackPlan = "capability_registry_fallback_plans"
const TableCapabilityRegistryHealthProbeResult = "capability_registry_health_probe_results"
const TableCapabilityRegistryDiscoveryCache = "capability_registry_discovery_cache"

const TableIntegrationGatewayRoute = "integration_gateway_routes"
const TableIntegrationGatewayRouteVersion = "integration_gateway_route_versions"
const TableIntegrationGatewayInvocationLog = "integration_gateway_invocation_logs"
const TableIntegrationGatewayEventPublication = "integration_gateway_event_publications"

const TableEventTopics = "event_topics"
const TableEventAclBindings = "event_acl_bindings"
const TableEventEnvelopes = "event_envelopes"
const TableEventDeliveryAttempts = "event_delivery_attempts"
const TableEventDlqMessages = "event_dlq_messages"
const TableEventSubscriptionOffsets = "event_subscription_offsets"
const TableEventReplayRequests = "event_replay_requests"
const TableEventAuthCapabilities = "event_auth_capabilities"
const TableEventAuthGrants = "event_auth_grants"
const TableEventAuthGrantCapabilities = "event_auth_grant_capabilities"
const TableEventAuthGrantConditions = "event_auth_grant_conditions"
const TableEventAuthApprovalTickets = "event_auth_approval_tickets"
const TableEventAuthGrantTemplates = "event_auth_grant_templates"

const TableWorkflowDefinitions = "workflow_definitions"
const TableWorkflowInstances = "workflow_instances"
const TableWorkflowStepRecords = "workflow_step_records"
const TableWorkflowStepCompensations = "workflow_step_compensations"
const TableWorkflowAgentAssignments = "workflow_agent_assignments"
const TableWorkflowEvents = "workflow_events"

const TablePluginReleaseCandidates = "plugin_release_candidates"
const TablePluginReleasePlans = "plugin_release_plans"
const TablePluginReleaseCanaryRecords = "plugin_release_canary_records"
const TablePluginReleaseOfflinePackages = "plugin_release_offline_packages"
const TablePluginReleaseMarketplaceListings = "plugin_release_marketplace_listings"
const TablePluginReleaseLocalInstallSessions = "plugin_release_local_install_sessions"
const TablePluginImportRuns = "plugin_import_runs"
const TablePluginDebugReports = "plugin_debug_reports"
const TablePluginSandboxRuns = "plugin_sandbox_validation_runs"
const TableVersionGovernanceReports = "version_governance_reports"
const TablePluginCompatExceptions = "plugin_compat_exceptions"
const TableDevHotloadSessions = "dev_plugin_sessions"
const TableDevHotloadSessionEvents = "dev_plugin_session_events"

const TableKnowledgeSpaces = "knowledge_spaces"
const TableKnowledgePolicyTemplates = "knowledge_policy_template_versions"
const TableKnowledgeIngestionJobs = "knowledge_ingestion_jobs"
const TableKnowledgeArtifactBundles = "knowledge_artifact_bundles"
const TableKnowledgeFusionStrategies = "knowledge_fusion_strategy_versions"
const TableKnowledgeFeedbackCases = "knowledge_feedback_cases"
const TableKnowledgeIAMSyncTasks = "knowledge_iam_sync_tasks"
const TableKnowledgeAuditTrailEntries = "knowledge_audit_trail_entries"
const TableKnowledgeDeltaJobs = "knowledge_delta_jobs"
