[package]
name = "powerx-sdk"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "PowerX gRPC Rust SDK"
repository = "https://github.com/ArtisanCloud/PowerX"

[dependencies]
tonic = { version = "0.11", features = ["transport"] }
prost = "0.12"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
anyhow = "1"

[package.metadata.docs.rs]
all-features = true

