package plugingrants_test

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"net/http"
	"os"
	"strings"
	"testing"
	"time"

	stsv1 "github.com/ArtisanCloud/PowerX/api/grpc/gen/go/powerx/auth/sts/v1"
	pluginsvc "github.com/ArtisanCloud/PowerX/internal/service/plugin"
	"github.com/ArtisanCloud/PowerX/pkg/plugin_mgr"
	"github.com/google/uuid"
	"github.com/stretchr/testify/require"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

// Explicitly opt-in: uses the running development backend and its migrated DB.
// No existing plugin grants are changed; generated credentials never leave memory.
func TestLiveSessionSTSAndManifestRevocation(t *testing.T) {
	dsn, base, address := os.Getenv("POWERX_LIVE_TEST_DSN"), os.Getenv("POWERX_LIVE_TEST_URL"), os.Getenv("POWERX_LIVE_TEST_STS")
	if dsn == "" || base == "" || address == "" {
		t.Skip("live_acceptance_not_configured")
	}
	require.True(t, strings.HasPrefix(base, "http://127.0.0.1:"))
	require.True(t, strings.HasPrefix(address, "127.0.0.1:"))
	db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{Logger: logger.Default.LogMode(logger.Silent)})
	require.NoError(t, err)
	sqlDB, err := db.DB()
	require.NoError(t, err)
	t.Cleanup(func() { require.NoError(t, sqlDB.Close()) })
	ctx, cancel := context.WithTimeout(context.Background(), 6*time.Minute)
	defer cancel()
	var tenants []string
	require.NoError(t, db.Raw("SELECT t.uuid::text FROM iam_tenant t WHERE t.status = 1 AND t.deleted_at IS NULL ORDER BY EXISTS (SELECT 1 FROM ai_model_profiles p WHERE p.tenant_uuid=t.uuid::text AND p.modality='llm' AND p.deleted_at IS NULL) DESC, t.uuid LIMIT 2").Scan(&tenants).Error)
	require.Len(t, tenants, 2)
	connection, err := grpc.NewClient(address, grpc.WithTransportCredentials(insecure.NewCredentials()))
	require.NoError(t, err)
	defer connection.Close()
	sts := stsv1.NewSTSServiceClient(connection)
	svc := pluginsvc.NewTenantPluginInstanceService(db)
	const sessionCap = "com.corex.agent.session.manage"
	const statusCap = "com.corex.capabilities.grant_status.read"
	pluginID := "com.powerx.acceptance." + strings.ReplaceAll(uuid.NewString(), "-", "")
	otherID := pluginID + ".other"
	agentUUID := uuid.NewString()
	t.Cleanup(func() {
		// Every deletion is restricted to identifiers generated by this test.
		for _, table := range []string{"agent_service_invocations", "agent_service_messages", "agent_service_sessions"} {
			require.NoError(t, db.Exec("DELETE FROM "+table+" WHERE agent_uuid = ?", agentUUID).Error)
		}
		require.NoError(t, db.Exec("DELETE FROM agents WHERE uuid = ?", agentUUID).Error)
		require.NoError(t, db.Exec("DELETE FROM plugin_instance_configs WHERE plugin_id IN (?, ?)", pluginID, otherID).Error)
	})
	issue := func(tenant, id string) string {
		_, clientID, secret, err := svc.Enable(ctx, tenant, plugin_mgr.Plugin{ID: id, Version: "acceptance", RequiredCapabilities: []string{sessionCap, statusCap, "com.corex.agent.invoke"}}, nil)
		require.NoError(t, err)
		response, err := sts.Exchange(ctx, &stsv1.ExchangeRequest{ClientId: clientID, ClientSecret: secret, Audience: "powerx:api", Scope: "access", TtlSeconds: 300})
		require.NoError(t, err)
		require.NotEmpty(t, response.GetData().GetAccessToken())
		return response.GetData().GetAccessToken()
	}
	token := issue(tenants[0], pluginID)
	otherToken := issue(tenants[0], otherID)
	crossToken := issue(tenants[1], pluginID)
	require.NoError(t, db.Exec("INSERT INTO agents (uuid,tenant_uuid,key,name,env,status,owner_plugin_id) VALUES (?,?,?,?,?,?,?)", agentUUID, tenants[0], pluginID, pluginID, "dev", "active", pluginID).Error)
	client := &http.Client{Timeout: 10 * time.Second}
	request := func(method, path, credential string, body any, key string, want int, reason string) map[string]any {
		var raw []byte
		if body != nil {
			raw, err = json.Marshal(body)
			require.NoError(t, err)
		}
		req, err := http.NewRequestWithContext(ctx, method, base+path, bytes.NewReader(raw))
		require.NoError(t, err)
		if credential != "" {
			req.Header.Set("Authorization", "Bearer "+credential)
		}
		req.Header.Set("Content-Type", "application/json")
		if key != "" {
			req.Header.Set("Idempotency-Key", key)
		}
		resp, err := client.Do(req)
		require.NoError(t, err)
		payload, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
		resp.Body.Close()
		require.NoError(t, err)
		require.Equal(t, want, resp.StatusCode, "%s %s: %s", method, path, payload)
		var decoded map[string]any
		require.NoError(t, json.Unmarshal(payload, &decoded))
		if reason != "" {
			require.Equal(t, reason, decoded["reason_code"])
			require.Equal(t, reason, decoded["error_code"])
		}
		data, _ := decoded["data"].(map[string]any)
		return data
	}
	const root = "/api/v1/tenant/agent/sessions"
	request("GET", root, "", nil, "", 401, "AGENT_SESSION_UNAUTHORIZED")
	request("GET", root, "invalid", nil, "", 401, "AGENT_SESSION_UNAUTHORIZED")
	request("GET", root+"/123", token, nil, "", 400, "AGENT_SESSION_INVALID_ARGUMENT")
	request("POST", root, token, map[string]any{"agent_uuid": agentUUID, "tenant_uuid": tenants[0]}, "", 400, "AGENT_SESSION_INVALID_ARGUMENT")
	created := request("POST", root, token, map[string]any{"agent_uuid": agentUUID, "title": ""}, "", 201, "")
	session, ok := created["session_uuid"].(string)
	require.True(t, ok)
	path := root + "/" + session
	request("GET", path, token, nil, "", 200, "")
	request("GET", path, otherToken, nil, "", 404, "AGENT_SESSION_NOT_FOUND")
	request("GET", path, crossToken, nil, "", 404, "AGENT_SESSION_NOT_FOUND")
	message := map[string]any{"role": "user", "content": "acceptance"}
	first := request("POST", path+"/messages", token, message, "append", 201, "")
	second := request("POST", path+"/messages", token, message, "append", 201, "")
	require.Equal(t, first["message_uuid"], second["message_uuid"])
	request("POST", path+"/messages", token, map[string]any{"role": "user", "content": "changed"}, "append", 409, "AGENT_SESSION_CONFLICT")
	request("GET", path+"/messages?page=1&page_size=10", token, nil, "", 200, "")
	if os.Getenv("POWERX_LIVE_TEST_INVOKE") == "1" {
		run := request("POST", path+"/invocations", token, map[string]any{"message_uuid": first["message_uuid"]}, "invoke", 202, "")
		runUUID, ok := run["invocation_uuid"].(string)
		require.True(t, ok)
		runPath := path + "/invocations/" + runUUID
		var final map[string]any
		for deadline := time.Now().Add(4 * time.Minute); time.Now().Before(deadline); {
			final = request("GET", runPath, token, nil, "", 200, "")
			if final["status"] == "succeeded" || final["status"] == "failed" || final["status"] == "cancelled" {
				break
			}
			time.Sleep(time.Second)
		}
		if final["status"] == "running" || final["status"] == "cancelling" {
			request("POST", runPath+"/cancel", token, nil, "", 202, "")
			for i := 0; i < 10; i++ {
				stopped := request("GET", runPath, token, nil, "", 200, "")
				if stopped["status"] == "cancelled" {
					break
				}
				time.Sleep(time.Second)
			}
		}
		require.Equal(t, "succeeded", final["status"], "invocation=%s reason=%v", runUUID, final["reason_code"])
		req, err := http.NewRequestWithContext(ctx, "GET", base+runPath+"/events", nil)
		require.NoError(t, err)
		req.Header.Set("Authorization", "Bearer "+token)
		response, err := client.Do(req)
		require.NoError(t, err)
		payload, err := io.ReadAll(io.LimitReader(response.Body, 1<<20))
		response.Body.Close()
		require.NoError(t, err)
		require.Equal(t, 200, response.StatusCode)
		require.Contains(t, string(payload), "event:final")
		require.Contains(t, string(payload), "event:end")
		replayed := request("POST", path+"/invocations", token, map[string]any{"message_uuid": first["message_uuid"]}, "invoke", 202, "")
		require.Equal(t, runUUID, replayed["invocation_uuid"])
		t.Log("live_runtime_invoke_succeeded_sse_terminal_replay_passed")
		// A closed SSE subscription must not cancel execution. Only the explicit
		// cancel operation may transition the durable invocation to cancelled.
		next := request("POST", path+"/messages", token, message, "cancel-message", 201, "")
		cancelRun := request("POST", path+"/invocations", token, map[string]any{"message_uuid": next["message_uuid"]}, "cancel-run", 202, "")
		cancelPath := path + "/invocations/" + cancelRun["invocation_uuid"].(string)
		subscribe, err := http.NewRequestWithContext(ctx, "GET", base+cancelPath+"/events", nil)
		require.NoError(t, err)
		subscribe.Header.Set("Authorization", "Bearer "+token)
		stream, err := client.Do(subscribe)
		require.NoError(t, err)
		var firstByte [1]byte
		_, err = stream.Body.Read(firstByte[:])
		require.NoError(t, err)
		stream.Body.Close()
		observed := request("GET", cancelPath, token, nil, "", 200, "")
		require.NotEqual(t, "cancelled", observed["status"])
		request("POST", cancelPath+"/cancel", token, nil, "", 202, "")
		for i := 0; i < 15; i++ {
			observed = request("GET", cancelPath, token, nil, "", 200, "")
			if observed["status"] == "cancelled" {
				break
			}
			time.Sleep(time.Second)
		}
		require.Equal(t, "cancelled", observed["status"])
		// Unconfigured fixture environment proves asynchronous dependency failure
		// without interrupting the real database/provider or any existing agent.
		require.NoError(t, db.Exec("UPDATE agents SET env = ? WHERE uuid = ?", "acceptance-unconfigured", agentUUID).Error)
		failedMessage := request("POST", path+"/messages", token, message, "failed-message", 201, "")
		failedRun := request("POST", path+"/invocations", token, map[string]any{"message_uuid": failedMessage["message_uuid"]}, "failed-run", 202, "")
		failedPath := path + "/invocations/" + failedRun["invocation_uuid"].(string)
		for i := 0; i < 15; i++ {
			observed = request("GET", failedPath, token, nil, "", 200, "")
			if observed["status"] == "failed" {
				break
			}
			time.Sleep(time.Second)
		}
		require.Equal(t, "failed", observed["status"])
		require.Equal(t, "AGENT_SESSION_UPSTREAM_DEPENDENCY", observed["reason_code"])
		req, err = http.NewRequestWithContext(ctx, "GET", base+failedPath+"/events", nil)
		require.NoError(t, err)
		req.Header.Set("Authorization", "Bearer "+token)
		response, err = client.Do(req)
		require.NoError(t, err)
		payload, err = io.ReadAll(io.LimitReader(response.Body, 1<<20))
		response.Body.Close()
		require.NoError(t, err)
		require.Contains(t, string(payload), "event:error")
		require.Contains(t, string(payload), "event:end")
		t.Log("live_sse_disconnect_explicit_cancel_dependency_failure_passed")
	}
	request("PATCH", path, token, map[string]any{"title": ""}, "", 200, "")
	request("POST", path+"/archive", token, nil, "", 200, "")
	request("POST", path+"/messages", token, message, "archived", 409, "AGENT_SESSION_CONFLICT")
	request("DELETE", path, token, nil, "", 200, "")
	request("GET", path, token, nil, "", 404, "AGENT_SESSION_NOT_FOUND")
	// Re-enable the same fixture with a reduced manifest: retain status access,
	// revoke only Session. The original STS token must fail immediately.
	_, _, _, err = svc.Enable(ctx, tenants[0], plugin_mgr.Plugin{ID: pluginID, Version: "acceptance", RequiredCapabilities: []string{statusCap}}, nil)
	require.NoError(t, err)
	request("GET", root, token, nil, "", 403, "AGENT_SESSION_FORBIDDEN")
	state := request("POST", "/api/v1/tenant/capabilities:grant-status", token, map[string]any{"capability_ids": []string{sessionCap}}, "", 200, "")
	items, ok := state["items"].([]any)
	require.True(t, ok)
	require.Len(t, items, 1)
	require.Equal(t, "not_granted", items[0].(map[string]any)["status"])
	for i := 0; i < 2; i++ {
		_, _, _, err = svc.Enable(ctx, tenants[0], plugin_mgr.Plugin{ID: pluginID, Version: "acceptance", RequiredCapabilities: []string{}}, nil)
		require.NoError(t, err)
		request("GET", root, token, nil, "", 403, "AGENT_SESSION_FORBIDDEN")
	}
	t.Log("live_sts_exchange_session_crud_isolation_idempotency_old_token_revocation_passed")
}
